### ISSUE TITLE
Incorrect dependency in setup.py

### ISSUE THREAD

**Issue by steve-mavens** [smheidrich/py-json-stream-rs-tokenizer#51]
This line appears in setup.py: `"si-prefix>=1.2<2"`

Assuming you mean >=1.2 and <2, then there's a missing comma. It should be `"si-prefix>=1.2,<2"` like the other dependencies above and below it.

poetry reports this as a warning while solving my environment that includes json-stream. I'm not using the "benchmark" extra, so it doesn't inconvenience me other than displaying the warning. If I were using it then poetry says it would ignore the constraint, which I suspect means it would install some version of si-prefix that might be outside the intended range. Or it might mean that it wouldn't install si-prefix at all: I haven't checked.

**Comment by smheidrich** [comment]
Thanks for spotting and reporting this! It should be fixed in 0.4.14.

**Comment by steve-mavens** [comment]
Confirmed 0.4.14 works for me, thank you!
