### ISSUE TITLE
Moving away from setup tools

### ISSUE THREAD

**Issue by kpcyrd** [smheidrich/py-json-stream-rs-tokenizer#88]
hello!

This project currently depends on setuptools-rust, from what I understand setuptools is deprecated and the project should instead use something like maturin to build a wheel. :)

Is there a way to build a wheel with the current tools? (I'm by far not an expert on this)

Thank you!

**Comment by smheidrich** [comment]
Exactly what @daggaz said. Maturin is a million times more convenient but without optional extension support we can't use it.

@kpcyrd I also haven't heard anything about setuptools or setuptools-rust getting deprecated, could you share a link if there were any announcements or plans of moving in that direction?

**Comment by kpcyrd** [comment]
It seems I've confused setuptools and setup.py: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html

I also noticed `python -m build` works as expected and `setup.py` doesn't have to be used, so nothing to do here. :upside_down_face: 

Thanks and sorry for bothering!

**Comment by smheidrich** [comment]
I'll get rid of `setup.py` in favor of `setup.cfg` soon given that https://github.com/PyO3/setuptools-rust/issues/208 has recently been implemented :+1:
